# Generated by Django 5.0.1 on 2024-04-17 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rent',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='rent',
            name='lng',
        ),
        migrations.AddField(
            model_name='rent',
            name='end_lat',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='rent',
            name='end_lng',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='rent',
            name='start_lat',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='rent',
            name='start_lng',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
