# Generated by Django 5.0.1 on 2024-04-24 21:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='retweeted_by',
            field=models.ManyToManyField(blank=True, default=None, related_name='retweeted', to=settings.AUTH_USER_MODEL),
        ),
    ]
